version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Development.Dockerfile
    command: uvicorn ex_back.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - ex_back_shared_network
    volumes:
      - ./:/ex_back
networks:
  ex_back_shared_network:
    external: true

