version: '3.8'

services:

  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - TESTING=${TESTING}
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@web-db:5432/${PG_DB}
      - DATABASE_TEST_URL=postgres://${PG_USER}:${PG_PASSWORD}@web-db:5432/${PG_DB_TEST}
#    depends_on:
#      - web-db
    volumes:
      - ./:/usr/src/app

#  web-db:
#    build:
#      context: ./db
#      dockerfile: Dockerfile
#    volumes:
#        - postgres_data:/var/lib/postgresql/data/
#    expose:
#      - 5432
#    environment:
#      - POSTGRES_USER=${PG_USER}
#      - POSTGRES_PASSWORD=${PG_PASSWORD}

volumes:
  postgres_data: