version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # Web UI
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}" # AMQP
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - ex_back_shared_network

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - ex_back_shared_network

networks:
  ex_back_shared_network:
    external: true
