version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Production.Dockerfile
    command: uvicorn ex_back.main:app --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}
    networks:
      - ex_back_shared_network
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  ex_back_shared_network:
    external: true
