version: '3.8'

services:

  web:
    build: .
    command: uvicorn ex_back.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - TESTING=${TESTING}
      - DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}
      - DATABASE_TEST_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB_TEST}
    depends_on:
      - db
    volumes:
      - ./:/ex_back

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

volumes:
  postgres_data: