version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"  # Port for the management web interface
      - "5672:5672"    # Default RabbitMQ listener port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - ex_back_shared_network

networks:
  ex_back_shared_network:
    external: true