version: '3.8'

services:

  web:
    build: .
    command: uvicorn ex_back.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - TESTING=${TESTING}
      - DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}
      - TEST_DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@db:5432/${TEST_DB}
    networks:
      - shared_network
    volumes:
      - ./:/ex_back

networks:
  shared_network:
    external: true
