version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Production.Dockerfile
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 ex_back.main:app
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
      - ex_back_shared_network
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  ex_back_shared_network:
    external: true
