version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - ex_back_shared_network
    env_file:
      - ./.env
volumes:
  postgres_data:
networks:
  ex_back_shared_network:
    external: true
