version: '3.8'

services:

  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - TESTING=${TESTING}
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@web-db:5432/${PG_DB}
      - DATABASE_TEST_URL=postgres://${PG_USER}:${PG_PASSWORD}@web-db:5432/${PG_DB_TEST}
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

  rabbitmq:
      image: 'rabbitmq:3-management'
      environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
      ports:
        - '5672:5672'
        - '15672:15672'
  worker:
    build: .
    command: celery -A your_application.celery_app worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - rabbitmq

volumes:
  postgres_data: