"""initial migration

Revision ID: 6615892c2c5f
Revises: 
Create Date: 2023-08-22 00:35:47.290650

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6615892c2c5f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "type",
            postgresql.ENUM("MARKET", "LIMIT", name="ordertype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "side",
            postgresql.ENUM("BUY", "SELL", name="orderside"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("instrument", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "limit_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="orders_pkey"),
    )
    # ### end Alembic commands ###
