name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PG_USER: excercise_user
      PG_PASSWORD: excercise_password
      PG_DB: excercise_db
      PG_HOST: db
      PG_PORT: 5432
      TEST_DB: excercise_test_db
      RABBIT_MQ_URL: amqp://guest:guest@localhost:5672/
      CELERY_BROKER_URL: amqp://guest:guest@localhost:5672/
      ENVIRONMENT: production

    steps:
    - name: Set up derived env variables
      run: echo "TEST_DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${TEST_DB}" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env
      run: touch .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Run tests
      run: |
        scripts/run.sh test 
